#!/bin/bash

# Install the node dependencies
npm install --yes

# Backup existing configuration files
if [ ! -f /usr/local/hestia/nginx/conf/nginx.conf_quickstart-sav ]; then
    cp /usr/local/hestia/nginx/conf/nginx.conf /usr/local/hestia/nginx/conf/nginx.conf_quickstart-sav
fi

# Check if nginx.conf_quickstart is already included in nginx.conf
if ! grep -q 'nginx.conf_quickstart' /usr/local/hestia/nginx/conf/nginx.conf; then

    # Include a reference to our nginx configuration file
    cp /usr/local/hestia/plugins/quickstart/nginx.conf_quickstart /usr/local/hestia/data/hcpp/nginx.conf_quickstart
    sed -i '/location \/ {/i include /usr/local/hestia/data/hcpp/nginx.conf_quickstart;' /usr/local/hestia/nginx/conf/nginx.conf
fi

# Check if upload-server.js is already running as admin
PID=$(ps -aux | grep upload-server.js | grep admin | grep -v grep | awk '{print $2}')

if [ -z "$PID" ]; then
    # If no PID is found, run the script as admin
    runuser -u admin -- "/usr/local/hestia/plugins/quickstart/start-upload-server.sh"
else
    echo "upload-server.js is already running with PID $PID"
fi

# Restart services
service hestia restart

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin Quickstart "<span>&#127937;</span> Quickstart plugin has finished installing."
